### ISSUE TITLE
 Error: Cannot find module 'core-js/modules/es.symbol.description.js'

### ISSUE THREAD

**Issue by finnlewis** [wingsuit-designsystem/wingsuit#267]
**Describe the bug**

Sorry if I'm missing something obvious, but I am just trying to set up a Drupal wingsuit theme and I'm seeing the same error whichever way I go.

`Error: Cannot find module 'core-js/modules/es.symbol.description.js'`

**To Reproduce**

Looking at https://github.com/wingsuit-designsystem/wingsuit#quickstart 

I've got a Drupal site installed.

```
cd themes/custom
npx @wingsuit-designsystem/cli init
```

And this is what I get: 

```

$ npx @wingsuit-designsystem/cli init
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.symbol.description.js'
Require stack:
- /home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/dist/cli.js
- /home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/dist/cli.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/dist/cli.js',
    '/home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/bin/index.js'
  ]
}

```

**To Reproduce the BLT route**

Also, following the https://github.com/wingsuit-designsystem/wingsuit-kickstarter route: 

When I get to: 

```
 ./vendor/bin/blt setup
```
I get a similar error: 
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.symbol.description.js'
Require stack:
- /home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/dist/cli.js
- /home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/dist/cli.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/dist/cli.js',
    '/home/finn/.npm/_npx/0509b4e64139b452/node_modules/@wingsuit-designsystem/cli/bin/index.js'
  ]
}
sh: 1: cd: can't cd to wingsuit
 [ExecStack]  Exit code 2  Time 2.293s
 [error]  Executing target-hook frontend-reqs failed.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
 [error]  Command `source:build:frontend-reqs ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
 [error]  Command `source:build:frontend ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
The command failed. This often indicates a problem with your configuration. Review the command output above for more detailed errors, and consider re-running with verbose output for more information.
 [error]  Command `source:build ` exited with code 1.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
```

```
**Expected behavior**
Not sure, I'm just trying to set it up and test.

**Desktop (please complete the following information):**

- Ubuntu 22.04
- PHP 8.1.7
- Node v16.13.0
- yarn 1.22.19
- npx 8.1.0


Any help or suggestions gratefully received!

**Comment by christianwiedemann** [comment]
Hm strange. It works for me. The package "core-js" is somehow missing. Will check it.

**Comment by christianwiedemann** [comment]
Can you try npx @wingsuit-designsystem/cli init --branch master

**Comment by blackbart420** [comment]
@christianwiedemann  I just tried it but I got the same error

**Comment by bowiechang** [comment]
Thanks @christianwiedemann, I've tried `npx @wingsuit-designsystem/cli init --branch master` and gotten the same error, watching this issue.

**Comment by christianwiedemann** [comment]
I released 1.2.8 with core-js included in wingsuit/core. Give it a try.

**Comment by blackbart420** [comment]
Thank you very much @christianwiedemann ! The error is gone :)

**Comment by finnlewis** [comment]
Just to confirm, I can now install with 

`npx @wingsuit-designsystem/cli@1.2.8 init
`

Thanks @christianwiedemann !

**Comment by finnlewis** [comment]
However, it the error persists when not specifying a version. 

`npx @wingsuit-designsystem/cli init`

Which then means the BLT route still does not work.

**Comment by finnlewis** [comment]
So this is what worked for me in Drupal in the end, for the 1.x branch.

Fresh install of Drupal 9.

```
composer require 'drupal/wingsuit_companion:^2.1'
composer require 'drupal/ui_patterns:^1.5'
composer require 'drupal/components:^2.4'

drush en components wingsuit_companion wingsuit_ui_patterns
cd themes/custom
nvm use 16
npx @wingsuit-designsystem/cli@1.2.8 init -k tailwind 
```

This fires up Storybook on completion.

ctrl C (^C) to get out of that 

Build the Drupal theme assets with: 

```
cd wingsuit
yarn dev:drupal

```
In Drupal, edit the dist path at /admin/wingsuit-companion/form/config and set to: 

```
themes/custom/wingsuit/dist/app-drupal
```

At /admin/appearance, install wingsuit theme then set to default.

Clear the cache

I can now see various components on the Drupal theme, not laid out particularly well, but it's a start! 

![image](https://github.com/wingsuit-designsystem/wingsuit/assets/326588/0070e7fa-87b4-41bb-bf5b-65602a03065d)
